apiVersion: v1
kind: Service
metadata:
  name: kubernetes-demo
spec:
  type: NodePort
  ports:
    - nodePort: 30120
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: kubernetes-demo